### PR TITLE
add 'nextpnr-gowin' tests

### PR DESCRIPTION
**Pull request by racerxdl**
Added nextpnr-gowin help tests.

### CODE REVIEW

**Comment by umarcor** [comment]
@racerxdl LGTM. Any reason for it to be a draft?

**Comment by racerxdl** [comment]
@umarcor well I just wanted to mention in the pull request inside https://github.com/hdl/containers (I'm writing it right now)

**Comment by umarcor** [comment]
Then, if you are good, I'll merge this now. That way, when you push the PR to hdl/containers you can bump the submodule for it to include this change. Otherwise, the container test will fail because this file won't exist!

**Comment by racerxdl** [comment]
Sure @umarcor , I tested locally everything and it worked. It correctly checks for the existence of nextpnr_gowin ^^

**Pull request merged**
